### ISSUE TITLE
Change the Design of the Glasomer questionnaire.

### ISSUE THREAD

**Issue by dafinaolluri** [crtarsorg/glasomer.rs-v2#1]
**Acceptance Criteria**

- [x] Header
- [x] Šta je Glasomer page ?

**Comment by ferideadili** [comment]
![glasomer-frontend](https://cloud.githubusercontent.com/assets/3279668/23630027/c7e5051c-02b9-11e7-9321-190115c89950.png)
![Uploading glasomer-frontend-v2.png…]()
![Uploading glasomer-mobile-version.png…]()

**Comment by dafinaolluri** [comment]
@ferideadili We still need the approval for the colors from CRTA designer. We can re-open this when they get back with answers.
