### ISSUE TITLE
Front-End Page: On the last page of the questionnaire you should delete the field “sledeći”, because there is no next page. Also, on the first page you should delete “prethodni”.  

### ISSUE THREAD

**Issue by dafinaolluri** [crtarsorg/glasomer.rs-v2#27]
Please the screenshot below:

![image](https://cloud.githubusercontent.com/assets/24916965/24247723/13f99c04-0fcd-11e7-882f-16f3d1d7164a.png)

**Comment by ferideadili** [comment]
@dafinaolluri I think the screenshot is wrong here, from the description I think its for the form where the user is answering the questions.

**Comment by dafinaolluri** [comment]
@ferideadili yes, you are right.
