### ISSUE TITLE
Delete the “poslednja” and “sledeca” in “Uporedi odgovore” section.

### ISSUE THREAD

**Issue by dafinaolluri** [crtarsorg/glasomer.rs-v2#29]
Please see the screenshot below:

![image](https://cloud.githubusercontent.com/assets/24916965/24247837/99670ff2-0fcd-11e7-9cfc-d4da12ad2504.png)

**Comment by artaabdullahu** [comment]
@ferideadili The button "Prethodna" shoul be center, in every size of browser.
![screenshot from 2017-03-27 09 01 41](https://cloud.githubusercontent.com/assets/21961919/24346414/820663bc-12d4-11e7-888a-c97c35bab9bc.png)
