### ISSUE TITLE
Admin should be able to edit text in the sta-je-glasomer page.

### ISSUE THREAD

**Issue by georgeslabreche** [crtarsorg/glasomer.rs-v2#48]
Consult with @partini on the best WYSIWYG text editor to use.
As a rule, any content that is dependent on the election year needs to be editable by Admin.

We should also probably change the slug of the about glasomer page from whatis to sta-je-glasomer.

**Comment by ferideadili** [comment]
url slug changed to sta-je glasomer

**Comment by georgeslabreche** [comment]
@ferideadili @artaabdullahu did we only change the slug or did we implement the admin WYSIWYG text editor for the about page? If we only did slug then this task should not be in done. Also, please note that the admin WYSIWYG text editor for the about page is not a priority.

**Comment by ferideadili** [comment]
@georgeslabreche, no the admin WYSIWYG text editor was implemented too, the text is displayed from the database, depending on the year enabled.
